name: 'Test action'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
      FDO_APIKEY: ${{ secrets.FDO_APIKEY }}
      ALT3_HOME: data
      ALT3_SCRIPTS: code/scripts
      ALT3_LEAGUES_DIR: data/docs/assets/leagues
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: code
    - name: 'setup R'
      uses: r-lib/actions/setup-r@v2
    - name: 'setup R dependencies'
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        working-directory: code/pkg
    - name: 'install the alt3code package'
      run: R CMD INSTALL code/pkg
    - name: 'where we are'
      run: pwd
    - name: 'show an environment variable'
      run: echo $ALT3_SCRIPTS
