name: 'Update all leagues'

# **What it does**: Updates the alt3.uk website daily.

on:
  workflow_dispatch:
  schedule:
    - cron: "49 22 * * *"

jobs:
  job-to-update-all-leagues:
    runs-on: ubuntu-20.04
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
      FDO_APIKEY: ${{ secrets.FDO_APIKEY }}
      ALT3_HOME: ${{ github.workspace }}/data
      ALT3_CODE: ${{ github.workspace }}/code/pkg
      ALT3_SCRIPTS: ${{ github.workspace }}/code/scripts
      ALT3_LEAGUES_DIR: ${{ github.workspace }}/data/docs/assets/leagues/
      ALT3_CURRENT_SEASON: 2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: code
    - name: 'Setup R'
      uses: r-lib/actions/setup-r@v2
    - name: 'Setup R dependencies'
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        working-directory: code/pkg
    - name: Checkout alt3 repo
      uses: actions/checkout@v3
      with:
        repository: DavidFirth/alt3
        path: data
        token: ${{ secrets.PAT }}
    - name: 'Run update-all.sh'
      run: bash "$ALT3_SCRIPTS"/update-all.sh
    - name: 'Push to github'
      run: |
        cd $ALT3_HOME
        git config --global user.name 'DavidFirth'
        git config --global user.email 'DavidFirth@users.noreply.github.com'
        git push
